name: Smoke Test - Account Settings

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    # This runs at 00:00 UTC (midnight) every other day
    - cron: "0 0 */2 * *"

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          PROVIDER_USERNAME: ${{ secrets.PROVIDER_USERNAME }}
          PROVIDER_PASSWORD: ${{ secrets.PROVIDER_PASSWORD }}
          PATIENT_USERNAME: ${{ secrets.PATIENT_USERNAME }}
          PATIENT_PASSWORD: ${{ secrets.PATIENT_PASSWORD }}
          COORDINATOR_USERNAME: ${{ secrets.COORDINATOR_USERNAME }}
          COORDINATOR_PASSWORD: ${{ secrets.COORDINATOR_PASSWORD }}
          SMOKE_PROVIDER_USERNAME: ${{ secrets.SMOKE_PROVIDER_USERNAME }}
          SMOKE_PROVIDER_PASSWORD: ${{ secrets.SMOKE_PROVIDER_PASSWORD }}
          SMOKE_PATIENT_USERNAME: ${{ secrets.SMOKE_PATIENT_USERNAME }}
          SMOKE_PATIENT_PASSWORD: ${{ secrets.SMOKE_PATIENT_PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: npx playwright test --project=smoketest-chromium
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
